from bot import CMD_SUFFIX


class _BotCommands:
    def __init__(self):
        self.StartCommand = f'start'
        self.MirrorCommand = f'mirror{CMD_SUFFIX}'
        self.UnzipMirrorCommand = f'unzipmirror{CMD_SUFFIX}'
        self.ZipMirrorCommand = f'zipmirror{CMD_SUFFIX}'
        self.QbMirrorCommand = f'qbmirror{CMD_SUFFIX}'
        self.QbUnzipMirrorCommand = f'qbunzipmirror{CMD_SUFFIX}'
        self.QbZipMirrorCommand = f'qbzipmirror{CMD_SUFFIX}'
        self.YtdlCommand = f'ytdl{CMD_SUFFIX}'
        self.YtdlZipCommand = f'ytdlzip{CMD_SUFFIX}'
        self.LeechCommand = f'leech{CMD_SUFFIX}'
        self.UnzipLeechCommand = f'unzipleech{CMD_SUFFIX}'
        self.ZipLeechCommand = f'zipleech{CMD_SUFFIX}'
        self.QbLeechCommand = f'qbleech{CMD_SUFFIX}'
        self.QbUnzipLeechCommand = f'qbunzipleech{CMD_SUFFIX}'
        self.QbZipLeechCommand = f'qbzipleech{CMD_SUFFIX}'
        self.YtdlLeechCommand = f'ytdlleech{CMD_SUFFIX}'
        self.YtdlZipLeechCommand = f'ytdlzipleech{CMD_SUFFIX}'
        self.CloneCommand = f'clone{CMD_SUFFIX}'
        self.CountCommand = f'count{CMD_SUFFIX}'
        self.DeleteCommand = f'del{CMD_SUFFIX}'
        self.CancelMirror = f'cancel{CMD_SUFFIX}'
        self.CancelAllCommand = f'cancelall{CMD_SUFFIX}'
        self.ListCommand = f'find{CMD_SUFFIX}'
        self.SearchCommand = f'search{CMD_SUFFIX}'
        self.StatusCommand = f'status{CMD_SUFFIX}'
        self.UsersCommand = f'users{CMD_SUFFIX}'
        self.AuthorizeCommand = f'authorize{CMD_SUFFIX}'
        self.UnAuthorizeCommand = f'unauthorize{CMD_SUFFIX}'
        self.AddSudoCommand = f'addsudo{CMD_SUFFIX}'
        self.RmSudoCommand = f'rmsudo{CMD_SUFFIX}'
        self.PingCommand = f'ping{CMD_SUFFIX}'
        self.RestartCommand = f'restart{CMD_SUFFIX}'
        self.StatsCommand = f'stats{CMD_SUFFIX}'
        self.HelpCommand = f'help'
        self.LogCommand = f'log{CMD_SUFFIX}'
        self.ShellCommand = f'shell{CMD_SUFFIX}'
        self.EvalCommand = f'eval{CMD_SUFFIX}'
        self.ExecCommand = f'exec{CMD_SUFFIX}'
        self.ClearLocalsCommand = f'clearlocals{CMD_SUFFIX}'
        self.BotSetCommand = f'bsetting{CMD_SUFFIX}'
        self.UserSetCommand = f'usetting{CMD_SUFFIX}'
        self.BtSelectCommand = f'btsel{CMD_SUFFIX}'
        self.RssCommand = f'rss{CMD_SUFFIX}'

BotCommands = _BotCommands()